---
- name: Read current cmdline
  changed_when: false
  failed_when: false
  register: __cmdline
  ansible.builtin.shell:
    cmd: grep GRUB_CMDLINE_LINUX_DEFAULT /etc/default/grub

- name: Append new cmdline
  when: "proxmox_iommu_cmdline not in __cmdline.stdout"
  notify: Update GRUB
  ansible.builtin.lineinfile:
    dest: /etc/default/grub
    regexp: 'GRUB_CMDLINE_LINUX_DEFAULT="(.*)"'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="\1 {{ proxmox_iommu_cmdline }}"'
    backrefs: true
