---
- name: Read current cmdline
  changed_when: false
  failed_when: false
  register: __cmdline
  ansible.builtin.command:
    cmd: cat /etc/kernel/cmdline

- name: Update grub cmdline
  when: "proxmox_iommu_cmdline not in __cmdline.stdout"
  notify: EFI Refresh
  block:
    - name: Remove the current cmdline
      ansible.builtin.file:
        path: /etc/kernel/cmdline
        state: absent

    - name: Write the new cmdline
      ansible.builtin.lineinfile:
        path: /etc/kernel/cmdline
        line: "{{ __cmdline.stdout }} {{ proxmox_iommu_cmdline }}"
        create: true
